Final_project/Final_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('pages/', include('django.contrib.flatpages.urls')),
    # Подключаем все адреса из приложения "advertisements" к главному приложению с префиксом ads/.
    path('', include('advertisements.urls')),
    path('accounts/', include('allauth.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('signup/', include('signup.urls')),
]

Final_project/signup/urls.py
from django.contrib.auth import views
from django.urls import path

from .views import BaseRegisterView

urlpatterns = [
    path('', BaseRegisterView.as_view(template_name='signup/signup.html'), name='signup'),
]

Final_project/advertisements/models.py
from django.contrib.auth.models import User
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.
from django.urls import reverse, reverse_lazy


class Advertisement(models.Model):
    '''
    Эта модель описывает объявления, которые создают пользователи.
    Объявления состоят из заголовка и текста, внутри которого могут быть картинки, встроенные видео и другой контент.
    Каждое объявление относится к одной из следующих категорий:
    Танки, Хилы, ДД, Торговцы, Гилдмастеры, Квестгиверы, Кузнецы, Кожевники, Зельевары, Мастера заклинаний.
    может иметь одну или несколько категорий. Модель должна включать следующие поля:
    - поле связанное с пользователем(автором объявления);
    - поле с выбором категории объявления;
    - автоматически добавляемая дата и время создания объявления;
    - заголовок объявления;
    - текст объявления.
    '''
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='Автор объявления')
    category = models.CharField(max_length=2,
                                choices=[('TN', 'Танки'), ('HE', 'Хилы'), ('DD', 'ДД'), ('ME', 'Торговцы'),
                                         ('GM', 'Гилдмастеры'), ('QG', 'Квестгиверы'), ('BS', 'Кузнецы'),
                                         ('TR', 'Кожевники'), ('PM', 'Зельевары'), ('MS', 'Мастера заклинаний')],
                                default='TN',
                                verbose_name='Категория объявления')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    title = models.CharField(max_length=255, verbose_name='Заголовок')
    content = RichTextField(blank=True, null=True, verbose_name='Содержание')

    def __str__(self):
        return f'{self.id}'

    def get_absolute_url(self):  # добавим путь, чтобы после создания перебрасывало на страницу с объявлениями.
        return f'/{self.id}'


class Feedback(models.Model):
    '''
    Эта модель описывает отклики на объявления, других пользователей. Отклик состоит из текста.
    Модель включает следующие поля:
        - поле связанное с пользователем(автором отклика);
        - поле связанное с объявлением(к которому добавлен отклик);
        - автоматически добавляемая дата и время создания отклика;
        - текст отклика.
    '''
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    ad = models.ForeignKey(Advertisement, on_delete=models.CASCADE, verbose_name='Объявление')
    creation_date = models.DateTimeField(auto_now_add=True, verbose_name='дата создания')
    text = models.CharField(max_length=256, verbose_name='Текст отклика')
    acception = models.BooleanField(default=False)

    def __str__(self):
        return f'{self.text} on {self.ad}'
    """"""
    def get_absolute_url(self):  # добавим абсолютный путь, чтобы после создания нас перебрасывало на страницу с товаром
        return reverse_lazy('ads_list')

Final_project/templates/ads/ad_create.html
{% extends 'flatpages/index.html' %}

{% block title %} Ad creation {% endblock title %}
 
{% block content %}
<h3>Создание публикации</h3>
<form method="POST">
    {% csrf_token %} 
    {{ form }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Добавить публикацию">
</form>
{% endblock content %}

Final_project/templates/ads/ad_detail.html
{% extends 'flatpages/index.html' %} <!--  наследуемся от шаблона default.html, который создавали для flatpages -->

{% block title %}
Подробности объявления            <!-- Название у нас будет Post Details -->
{% endblock title %}


{% block content %} <!-- В контенте на странице мы выводим саму публикацию, идентификатор которой был передан в url -->

<div class="card">
    <div class="card-content">
        <div class="media">
            <div class="media-left">
                <figure class="image is-48x48">
                <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </figure>
            </div>

        <div class="media-content">
            <p class="title is-4">{{ ad_detail.user }}</p>
            <p class="subtitle is-6">{{ ad_detail.creation_date | date:' d E Y G:i' }}</p>
        </div>
        <div class="media-right">
            <p class="title is-4">
                {{ ad_detail.get_category_display }}
            </p>
            <p class="subtitle is-6">
                Откликов {{feedbacks | length}}
            </p>
        </div>
    </div>
        <!-- Название статьи. -->
    <div class="content">
        <p class="title is-3 is-spaced has-text-centered">
            {{ ad_detail.title }}
        </p>
        <br>
        <!-- Содержание статьи. -->
        <p>
            {{ ad_detail.content }}
        </p>

        <!-- Если пользователь является автором статьи. -->
        {% if request.user.username == ad_detail.user.username %}

        <!-- Добавляем кнопку редактирования статьи. -->
        <div class="buttons is-right">
            <button class="button is-success">
                <span class="icon">
                    <i class="fa-solid fa-pen-to-square"></i>
                </span>
                <span>
                    <a href="{% url 'update_advertisement' ad_detail.id %}">
                        <p class="has-text-white">
                        Редактировать
                        </p>
                    </a>
                </span>
            </button>

            <!-- Добавляем кнопку удаления статьи. -->
            <button class="button is-danger">

                <span>
                    <a href="{% url 'delete_advertisement' ad_detail.id %}">
                        <p class="has-text-white">
                        Удалить
                        </p>
                    </a>
                </span>
                <span class="icon">
                    <i class="fa-solid fa-trash"></i>
                </span>
            </button>

        </div>
        {% endif %}
        </div>
    </div>
</div>



<!-- Раздел с откликами -->
<section class="section">
    <h1 class="title">На это объявление откликнулись {{feedbacks | length}} раз</h1>
    <h2 class="subtitle">

  </h2>
</section>


{% for feedback in ad_detail.feedback_set.all %}

<div class="card">
    <div class="card-content">
        <div class="media">
        <!-- Информация слева-->
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </figure>
            </div>

            <div class="media-content">
                <p class="title is-4">
                    {{ feedback.author | truncatewords:7 }}
                </p>
                <p class="subtitle is-6">{{ feedback.creation_date | date:' d E Y G:i' }}</p>
            </div>
        </div>
        <div class="content">
                {{ feedback.text }}
        </div>
    </div>
</div>
<br>


{% endfor %}
<!-- Если пользователь прошел аутентификацию -->
{% if request.user.is_authenticated %}

<section class="section">
    <h1 class="title">Хотите оставить комментарий? </h1>
    <h2 class="subtitle">
  </h2>
</section>

<!-- Добавляем форму для комментария.-->
<form method="POST" >{% csrf_token %}
    {{ form }}
    <div class="buttons is-right">
        <button type="submit" class="button is-link is-right">
            Отправить отклик
        </button>
    </div>
</form>

{% endif %}

{% endblock content %}

Final_project/templates/ads/ads_list.html
{% extends 'flatpages/index.html' %}

{% block title %} Список объявлений {% endblock title %}

{% block content %}

<section class="section">
        <h1 class="title">Свежие объявления от игроков на {{ time_now | date:'M d Y' }}</h1>
        <h2 class="subtitle">
        Здесь представлены последние добавленные <strong>объявления</strong>, читайте и откликайтесь.
        </h2>
</section>
    {% for ad in all_advertisement_list %}
<div class="card">
    <div class="card-content">
        <div class="media">
        <!-- Информация слева-->
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </figure>
            </div>

            <div class="media-content">
                <p class="title is-4">
                <a href="{% url 'ad_detail' ad.id %}">{{ ad.title | truncatewords:7 }}
                </a>
                </p>
                <p class="subtitle is-6">{{ ad.user }} от {{ ad.creation_date | date:' d E Y G:i' }} </p>
            </div>
            <!-- Информация справа-->
            <div class="media-right">
                <p class="title is-4">
                {{ ad.get_category_display }}
                </p>
                <p class="subtitle is-6">
                    Откликов {{ ad.feedback_set.all | length }}
                </p>
            </div>
        </div>
        <div class="content">
            {{ ad.content | truncatewords:20 }}
            <br>
        </div>
    </div>

{% if request.user.username == ad.user.username %}

    <footer class="card-footer">
            <!-- добавим ссылку на редактирование публикации-->
            <a href="{% url 'update_advertisement' ad.id %}" class="card-footer-item">Редактировать</a>
            <!-- добавим ссылку на удаление публикации-->
            <a href="{% url 'delete_advertisement' ad.id %}" class="card-footer-item">Удалить</a>
    </footer>
 {% endif %}
</div>



<br>

{% endfor %}

{% endblock content %}

Final_project/templates/ads/create.html
{% extends 'flatpages/index.html' %}

{% block title %} Ad creation {% endblock title %}
 
{% block content %}
<!-- Аннотация страницы-->
<section class="section">
        <h1 class="title">Создание объявления</h1>
        <h2 class="subtitle">
        Здесь вы можете <strong>создать</strong> свое собственное объявление. Заполните поля ниже.
        </h2>
</section>
<form method="POST">
    {% csrf_token %}


    {{ form.media }} <!-- Теперь нам нужна только готовая форма и кнопка -->
    {{ form.as_table }}

    <br>


    <input type="submit" value="Добавить публикацию">
</form>

{% endblock content %}

Final_project/templates/ads/delete.html
{% extends 'flatpages/index.html' %}
 
{% block title %} Удаление объявления {% endblock title %}
 
{% block content %}
<h2>Вы действительно хотите удалить это объявление?</h2>
<table>
    <thead>
        <th>Дата публикации</th>
        <th>Название</th>
    </thead>
    <tr>
        <td>{{ advertisement.creation_date | date:'d.M.Y' }}</td>
        <td>{{ advertisement.title }}</td>

    </tr>
</table>
 
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Удалить"></form>
{% endblock content %} 

Final_project/templates/ads/edit.html
{% extends 'flatpages/index.html' %}

{% block title %} Ad creation {% endblock title %}
 
{% block content %}
<!-- Аннотация страницы-->
<section class="section">
        <h1 class="title">Редактирование объявления</h1>
        <h2 class="subtitle">
        Здесь вы можете <strong>исправить</strong> свое объявление. Поправьте поля, расположенные ниже.
        </h2>
</section>
<form method="POST">
    {% csrf_token %} 
    {{ form.media }}
    {{ form.as_table }}<!-- Теперь нам нужна только готовая форма и кнопка -->
    <input type="submit" value="Применить изменения">
</form>
{% endblock content %}

Final_project/templates/ads/search.html
{% extends 'flatpages/index.html' %}

{% block title %} Ad Search List {% endblock title %}

{% block content %}
<!-- Аннотация страницы-->
<section class="section">
        <h1 class="title">Поиск объявлений</h1>
        <h2 class="subtitle">
        Здесь вы можете найти объявления. <strong>Фильтры</strong> ниже к вашим услугам)
        </h2>
</section>

<!-- Форма для поиска с фильтрами -->
<form method="GET">
    {{ filter.form }} <!-- Форму от фильтров за нас сделает Django. А вот кнопку, увы придётся делать самому -->
    <input type="submit" value="Найти">
</form>

<br>

{% for ad in filter.qs %} <!-- filter.qs, т.к. теперь мы забираем уже отобранную по каким-то параметрам информацию -->

<div class="card">
    <div class="card-content">
        <div class="media">
            <!-- Информация слева-->
            <div class="media-left">
                <figure class="image is-48x48">
                    <img src="https://bulma.io/images/placeholders/96x96.png" alt="Placeholder image">
                </figure>
            </div>

            <div class="media-content">
                <p class="title is-4">
                    <a href="{% url 'ad_detail' ad.id %}">{{ ad.title | truncatewords:7 }}
                    </a>
                </p>
                <p class="subtitle is-6">{{ ad.user }} от {{ ad.creation_date | date:'d.M.Y' }} </p>
            </div>
            <!-- Информация справа-->
            <div class="media-right">
                <p class="title is-4">
                    {{ ad.get_category_display }}
                </p>
                <p class="subtitle is-6">
                    Откликов {{ ad.feedback_set.all | length }}
                </p>
            </div>
        </div>
    </div>
</div>

<br> <!-- Отступ -->

{% endfor %}
{% endblock content %}